# Generated by Django 5.2 on 2025-04-09 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lan_scores.event')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lan_scores.player')),
            ],
        ),
    ]
