# Generated by Django 5.2 on 2025-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0002_eventplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='custom_pic_link',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='extra_link',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='extra_text',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='link',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
