# Generated by Django 5.2 on 2025-04-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0005_event_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='event',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='game',
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lan_scores.event')),
                ('score', models.ManyToManyField(null=True, through='lan_scores.Scores', to='lan_scores.player')),
            ],
        ),
        migrations.AddField(
            model_name='scores',
            name='GameInstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lan_scores.gameinstance'),
        ),
    ]
