# Generated by Django 5.2 on 2025-04-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0006_remove_scores_event_remove_scores_game_gameinstance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='score',
            field=models.ManyToManyField(through='lan_scores.Scores', to='lan_scores.player'),
        ),
    ]
