# Generated by Django 5.2 on 2025-04-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0008_gameinstance_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='GameInstance',
            new_name='game_instance',
        ),
    ]
