# Generated by Django 5.2 on 2025-04-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0009_rename_gameinstance_scores_game_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('link', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='hiden',
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='hiden',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
