# Generated by Django 5.2 on 2025-04-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0012_event_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='custom_pic_link',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True),
        ),
    ]
