# Generated by Django 5.2 on 2025-04-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0013_remove_event_custom_pic_link_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default=' new event', max_length=256),
        ),
    ]
