# Generated by Django 5.2 on 2025-04-29 18:30

from django.db import migrations

def create_event_admin_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='event_admin')

class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0014_alter_event_event_date_alter_event_name'),
    ]

    operations = [
        migrations.RunPython(create_event_admin_group),
    ]
