# Generated by Django 5.2 on 2025-04-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0003_alter_event_custom_pic_link_alter_game_extra_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='custom_pic_link',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='extra_link',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='game',
            name='extra_text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='player',
            name='link',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
