# Generated by Django 5.2 on 2025-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0004_alter_event_custom_pic_link_alter_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(through='lan_scores.EventPlayers', to='lan_scores.player'),
        ),
    ]
