# Generated by Django 5.2 on 2025-04-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan_scores', '0010_preveventlink_remove_game_hiden_gameinstance_hiden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='game_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lan_scores.gameinstance'),
        ),
    ]
